# vgg19 00 
name : 'vgg19_orig'
latent_dims: 512
model: 'VGG19Regression'
loss: 'MSELoss' # alternatively it could be L1Loss
epochs: 5
learning_rate: 0.001
batch_size: 32

proprioception_training_task: 'proprioception-cluttered'
proprioception_testing_task: 'proprioception-uncluttered'