# resnet-50 00 
name : 'resnet-50'

reductor_step_1: 512
proprio_step_1: 64
proprio_step_2: 16
output_size: 6

model: 'ResNetProprioTunedRegression'
loss: 'MSELoss' # alternatively it could be L1Loss
epochs: 10
learning_rate: 0.001
batch_size: 32

proprioception_training_task: 'proprio_sp_training'
proprioception_testing_task: 'proprio_sp_validation'