# vgg19 00 
name : 'vgg19-128'
latent_dims: 128
model: 'VGG19ProprioTunedRegression'
loss: 'MSELoss' # alternatively it could be L1Loss
epochs: 10
learning_rate: 0.001
batch_size: 32

proprioception_training_task: 'proprio_sp_training'
proprioception_testing_task: 'proprio_sp_validation'